### ISSUE TITLE
the link of "Build your first Polymer app" can not open

### ISSUE THREAD

**Issue by JaylyLiu** [Polymer/polymer-library-docs#11]
![image](https://user-images.githubusercontent.com/21221455/48931186-ed632800-ef2f-11e8-9eab-3b25dfe493ee.png)

I tried both in https://polymer-library.polymer-project.org/ and https://library.polymer-project.org/

**Comment by arthurevans** [comment]
This one should be fixed now (that tutorial isn't on the site anymore, link replaced with a more appropriate one). I'm working through other link errors ATM. Thanks for the report!
